######################################################################
#
# File name : tb_riscv_m_compile.do
# Created on: Wed Jun 19 12:56:15 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

D:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modeltech64_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../riscv_m.srcs/sources_1/new/alu.v" \
"../../../../riscv_m.srcs/sources_1/new/aludec.v" \
"../../../../riscv_m.srcs/sources_1/new/bu.v" \
"../../../../riscv_m.srcs/sources_1/new/controller.v" \
"../../../../riscv_m.srcs/sources_1/new/datapath.v" \
"../../../../riscv_m.srcs/sources_1/new/extend.v" \
"../../../../riscv_m.srcs/sources_1/new/flopr.v" \
"../../../../riscv_m.srcs/sources_1/new/flopren.v" \
"../../../../riscv_m.srcs/sources_1/new/instrdec.v" \
"../../../../riscv_m.srcs/sources_1/new/lsu.v" \
"../../../../riscv_m.srcs/sources_1/new/mainfsm.v" \
"../../../../riscv_m.srcs/sources_1/new/mem.v" \
"../../../../riscv_m.srcs/sources_1/new/mux2.v" \
"../../../../riscv_m.srcs/sources_1/new/mux3.v" \
"../../../../riscv_m.srcs/sources_1/new/regfile.v" \
"../../../../riscv_m.srcs/sources_1/new/riscv_m_top.v" \
"../../../../riscv_m.srcs/sources_1/new/riscv_multicycle.v" \
"../../../../riscv_m.srcs/sim_1/new/tb_riscv_m.v" \


# compile glbl module
D:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

