######################################################################
#
# File name : tb_riscv_m_simulate.do
# Created on: Wed Jun 19 12:56:16 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_riscv_m xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_riscv_m_wave.do}

view wave
view structure
view signals

do {tb_riscv_m.udo}

run 1000ns
