######################################################################
#
# File name : tb_riscv_m_wave.do
# Created on: Tue Jun 18 15:56:03 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
